### PR TITLE
Done Tests with coverage

### PR DESCRIPTION
**Pull request by SmooZzzie**
Done Tests for my application, waiting for checking.

------
Really sorry for 50+ commits which were uploaded accidently (idk how it happened :D)

### CODE REVIEW

**Comment by SmooZzzie** [comment]
week1.ProductTest > testShowInfo FAILED
    org.junit.ComparisonFailure at ProductTest.java:15
week1.TerminalTest > testDoSomeStatisticStuff FAILED
    org.junit.ComparisonFailure at TerminalTest.java:271

**Comment by SmooZzzie** [comment]
In Travis it shows like 2 of my tests are failed, but I ran them on my local branch in IDEA and everything is ok. What can it be? :\

**Comment by SmooZzzie** [comment]
image
Also, in Gradle everything is okay...

**Comment by presly808** [comment]
https://travis-ci.org/presly808/aco22/builds/300726112?utm_source=github_status&utm_medium=notification

your build was not success

**Comment by SmooZzzie** [comment]
image
Why they successfull in IDEA and Gradle, but failed in Travis?

**Comment by presly808** [comment]
try `gradlew check`

**Comment by SmooZzzie** [comment]
image
Already.

**Comment by presly808** [comment]
week1.ProductTest > testShowInfo FAILED
    org.junit.ComparisonFailure at ProductTest.java:15
week1.TerminalTest > testDoSomeStatisticStuff FAILED
    org.junit.ComparisonFailure at TerminalTest.java:271

or we will see tomorrow

**Comment by SmooZzzie** [comment]
But they are failed only in Travis, nowhere else. Something strange... Lets see tomorrow.

**Pull request merged**
